### ISSUE TITLE
postgrespool broken with Django 1.6 ('django_postgrespool' isn't an available database backend)

### ISSUE THREAD

**Issue by MRigal** [heroku-python/django-postgrespool#18]
This has the same syndrom than issue #17 but here the problem is clear:

Configuring the DB backend to postgrespool raises the following error:

django.core.exceptions.ImproperlyConfigured: 'django_postgrespool' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
Error was: cannot import name CursorWrapper

Indeed, with Django 1.6 (still in beta), the following line will crash
from django.db.backends.postgresql_psycopg2.base import CursorWrapper

**Comment by buzzeante** [comment]
Yep, the same is happening in my case :(

**Comment by mvid** [comment]
Bump

**Comment by cool-RR** [comment]
Here too.

**Comment by AlexHill** [comment]
Yet to look further into this, but error wrapping changed significantly as part of the persistent connections stuff in Django 1.6. The commit that breaks django_postgrespool is django/django@59a352087591a26023412cbcb830cd1d34fc9b99.

**Comment by ghost** [comment]
Any workarounds/developments on this?

**Comment by ssfrr** [comment]
As of 1.6 Django supports persistent connections with the MAX_CONN_AGE parameter. See https://docs.djangoproject.com/en/1.6/ref/databases/
