### ISSUE TITLE
Use Django 1.9+ location for postgresql backend

### ISSUE THREAD

**Issue by adamchainz** [heroku-python/django-postgrespool#31]
It was renamed from `django.db.backends.postgresql_psycopg2` to `django.db.backends.postgresql` in [Django Ticket #25175](https://code.djangoproject.com/ticket/25175) and there's an ongoing discussion about deprecating/removing the old name. Better to be future proof!

**Comment by adamchainz** [comment]
CC @jarshwah

**Comment by kennethreitz** [comment]
PR would be accepted!

**Comment by jarshwah** [comment]
Done.

**Comment by kennethreitz** [comment]
released!
