### ISSUE TITLE
'django_postgrespool' isn't an available database backend

### ISSUE THREAD

**Issue by tclancy** [heroku-python/django-postgrespool#6]
EDIT: this was an issue trying to run on Django < 1.4. Closing.

I've installed the package via pip and can do an import at the command line, but when I try to run the Django server, I get:

> django.core.exceptions.ImproperlyConfigured: 'django_postgrespool' isn't an available database backend. 
> Try using django.db.backends.XXX, where XXX is one of:
> 'dummy', 'mysql', 'oracle', 'postgresql', 'postgresql_psycopg2', 'sqlite3'

The site is using two databases and I've probably got some messed-up setting, but I can't figure out why it can't see the option. My settings.py looks like this:

``` python
DATABASES = {
    'default': {
        'HOST': 'localhost',
        'ENGINE': 'django_postgrespool',
        'NAME': 'db',
        'USER': 'postgres',
        'PASSWORD': 'pass'
    },
    'readonly': {
        'HOST': 'localhost',
        'ENGINE': 'django_postgrespool',
        'NAME': 'db',
        'USER': 'postgres',
        'PASSWORD': 'pass'
    }
}
```

**Comment by kennethreitz** [comment]
Hmm, are you sure that it's installed into the same environment? Perhaps it's not in the correct virtualenv?

**Comment by tclancy** [comment]
Yes. I can even 'import django_postgrespool' from python manage.py.shell, but if I have my db engine set to django_postgrespool it blows up.

**Comment by thurloat** [comment]
@tclancy I'm running into the same issue as well.

Not sure what the issue is.

## 

After further investigation, I believe it to be a symptom of testing it out on a django 1.3.x project.

**Comment by tclancy** [comment]
Oh, I was trying to use it on 1.3 as well. Is it 1.4+ only? Ah, looks like that's so: https://github.com/kennethreitz/django-postgrespool/pull/9

Oh well, this project needs to be updated anyway for the timezone support . . .

**Comment by kennethreitz** [comment]
Need to document this.

**Comment by tclancy** [comment]
Is it just a matter of sticking "Requires Django>=1.4 in the README"? I think I can handle that :)

**Comment by kennethreitz** [comment]
Go for it :)

**Comment by ldm616** [comment]
I'm getting this exact same error with Django 1.6.1.

```
File "/Users/malcolmlewis/django/anonqaproject/anonqa/lib/python2.7/site-packages/django/db/utils.py", line 131, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'django_postgrespool' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
Error was: cannot import name CursorWrapper
```

```
(anonqa)myhost:anonqaproject malcolmlewis$ cat requirements.txt 
APScheduler==2.1.2
Django==1.6.1
...
```

**Comment by tclancy** [comment]
See #18
